# Site settings
title: "Misam Abbas: Work And Talks"
description: "A brief work history"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Misam Abbas"
resume_title:                   "Staff AI Engineer, LinkedIn"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "gmail@misamabbas.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "-----"
resume_contact_address:         "Greater NY Area"

resume_header_contact_info:     "m@misamabbas.com"
display_header_contact_info:    "false"

resume_header_intro:  >-
  Misam Abbas is a Staff AI Engineer at LinkedIn currently working on GenAI Safety. 
  With over a decade of experience building large-scale ML systems, he has made significant contributions at Meta and Dropbox. 
  At Meta, he developed user representation models serving billions and created fairness metrics for recommender systems with wide adoption. 
  At Dropbox, he laid the foundations of Dash.ai's AI-powered universal search. 
  A conference speaker and co-author of ranking fairness research, his work eliminates critical bottlenecks to AI adoption while ensuring responsible deployment. 
  He holds an MBA from London Business School and B.Tech in Computer Science from IIT Delhi.

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
# resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_conferences:   true
resume_section_publications:  true
resume_section_associations:    true
resume_section_links:           true

# resume_section_projects:        true
# resume_section_skills:          true
# resume_section_recognition:     true
# resume_section_interests:       true



# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/misamabbas"
  resume_twitter_url:           "http://x.com/misamabbas"
  resume_linkedin_url:          "https://www.linkedin.com/in/misam"
  resume_website_url:           "http://work.misamabbas.com"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
